name: hund_pvt
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.3
  sweden_crs_transformations_4dart: ^1.0.1
  http: ^0.13.1
  flutter_spinkit: ^4.1.2
  permission_handler: ^7.1.0
  location: ^4.1.1
  fluster: ^1.2.0
  geocode: 1.0.1
  flutter_google_places: ^0.3.0
  firebase_auth: 1.1.4
  firebase_core: ^1.1.1
  google_sign_in: ^4.1.0
  firebase_dynamic_links: ^0.5.1
  clippy_flutter: ^1.1.1
  custom_info_window: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Cafe.png
    - assets/images/Cafe@2x.png
    - assets/images/Cafe@3x.png
    - assets/images/Dog_Park.png
    - assets/images/Restaurants.png
    - assets/images/Restaurants@2x.png
    - assets/images/Restaurants@3x.png
    - assets/images/Shop.png
    - assets/images/Shop@2x.png
    - assets/images/Shop@3x.png
    - assets/images/Trash_Cans.png
    - assets/images/Trash_Cans@2x.png
    - assets/images/Trash_Cans@3x.png
    - assets/images/Vet.png
    - assets/images/Vet@2x.png
    - assets/images/Vet@3x.png
    - assets/map_style.txt
    - assets/images/pawer.png
    - assets/images/veterinary_symbol.png
    - assets/images/bone_symbol.png
    - assets/images/dog_symbol.png
    - assets/images/restaurant_symbol.png
    - assets/images/cafe_symbol.png
    - assets/images/trashcan_symbol.png
    - assets/images/friends_symbol.png
    - assets/images/favourites_symbol.png
    - assets/images/fa-solid_paw.png
    - assets/images/dark-paw_symbol.png
    - assets/images/white-paw_symbol.png
    - assets/images/full_heart_symbol.png
    - assets/images/cancel_symbol.png
    - assets/images/heart_symbol.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
